version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      REDIS_NODE_1: redis-node-1:6371
#      REDIS_NODE_2: redis-node-2:6372
#      REDIS_NODE_3: redis-node-3:6373
#      REDIS_NODE_4: redis-node-1-replica:6374
#      REDIS_NODE_5: redis-node-2-replica:6375
#      REDIS_NODE_6: redis-node-3-replica:6376
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.10
    depends_on:
      - redis-master
#      - redis-slave1
#      - redis-slave2
      - redis-sentinel1
      - redis-sentinel2
      - redis-sentinel3
    networks:
      redis-net:
        ipv4_address: 172.20.0.10

  redis-master:
    container_name: "redis-master"
    image: redis:7.0.11
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      redis-net:
        ipv4_address: 172.20.0.30

#  redis-slave1:
#    container_name: "redis-slave1"
#    image: redis:7.0.11
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof redis-master 6379
#    depends_on:
#      - redis-master
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.31
#
#  redis-slave2:
#    container_name: "redis-slave2"
#    image: redis:7.0.11
#    ports:
#      - "6381:6379"
#    command: redis-server --slaveof redis-master 6379
#    depends_on:
#      - redis-master
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.32

  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis:7.0.11
    ports:
      - "5001:5001"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
#      - redis-slave1
#      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.33


  redis-sentinel2:
    container_name: 'redis-sentinel2'
    image: redis:7.0.11
    ports:
      - "5002:5002"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel2.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
#      - redis-slave1
#      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.34

  redis-sentinel3:
    container_name: 'redis-sentinel3'
    image: redis:7.0.11
    ports:
      - "5003:5003"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel3.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
#      - redis-slave1
#      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.35


#  redis-master:
#    container_name: redis-master
#    image: redis:7.0.11
#    ports:
#      - '6379:6379'
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.32
#  replica-1:
#    image: redis:7.0.11
#    ports:
#      - '6380:6379'
#    command: redis-server --slaveof redis-master 6379
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.33
#  replica-2:
#    image: redis:7.0.11
#    ports:
#      - '6381:6379'
#    command: redis-server --slaveof redis-master 6379
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.34

#  redis-cluster:
#    image: redis:7.0.11
#    command: redis-cli --cluster create 172.20.0.31:6371 172.20.0.32:6372 172.20.0.33:6373 172.20.0.34:6374 172.20.0.35:6375 172.20.0.36:6376 --cluster-replicas 1 --cluster-yes
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.30
#    depends_on:
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-1-replica
#      - redis-node-2-replica
#      - redis-node-3-replica
#  redis-node-1:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6371:6371'
#    volumes:
#      - ./redis-conf/node1.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.31
#  redis-node-2:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6372:6372'
#    volumes:
#      - ./redis-conf/node2.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.32
#  redis-node-3:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6373:6373'
#    volumes:
#      - ./redis-conf/node3.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.33
#  redis-node-1-replica:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6374:6374'
#    volumes:
#      - ./redis-conf/node1-replica.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.34
#  redis-node-2-replica:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6375:6375'
#    volumes:
#      - ./redis-conf/node2-replica.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.35
#  redis-node-3-replica:
#    image: redis:7.0.11
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - '6376:6376'
#    volumes:
#      - ./redis-conf/node3-replica.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      redis-net:
#        ipv4_address: 172.20.0.36
#
  wiremock:
    image: wiremock/wiremock
    ports:
      - '8090:8080'
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      redis-net:
        ipv4_address: 172.20.0.40
#
networks:
  redis-net:
    name: redis-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24