version: "3.9"

services:
  app:
    container_name: cache-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: sentinel
    ports:
      - "8080:8080"
    depends_on:
      - redis-master
      - wiremock
    networks:
      redis-net:
        ipv4_address: 172.20.0.10

  wiremock:
    image: wiremock/wiremock
    ports:
      - '8090:8080'
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      redis-net:
        ipv4_address: 172.20.0.20

  redis-master:
    container_name: "redis-master"
    image: redis:7.2-rc2-alpine
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      redis-net:
        ipv4_address: 172.20.0.30

  redis-slave1:
    container_name: "redis-slave-1"
    image: redis:7.2-rc2-alpine
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      redis-net:
        ipv4_address: 172.20.0.31

  redis-slave2:
    container_name: "redis-slave-2"
    image: redis:7.2-rc2-alpine
    ports:
      - "6381:6379"
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      redis-net:
        ipv4_address: 172.20.0.32

  redis-sentinel-1:
    container_name: 'redis-sentinel-1'
    image: redis:7.2-rc2-alpine
    ports:
      - "5001:5001"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./redis-conf-sentinel/sentinel1.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.33


  redis-sentinel-2:
    container_name: 'redis-sentinel-2'
    image: redis:7.2-rc2-alpine
    ports:
      - "5002:5002"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./redis-conf-sentinel/sentinel2.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.34

  redis-sentinel-3:
    container_name: 'redis-sentinel-3'
    image: redis:7.2-rc2-alpine
    ports:
      - "5003:5003"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./redis-conf-sentinel/sentinel3.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.20.0.35

networks:
  redis-net:
    name: redis-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24