version: "3.9"

services:
  app:
    container_name: cache-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: listener
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - wiremock
      - kafka
    networks:
      - redis-net

  redis:
    container_name: redis-standalone
    image: redis:7.2-rc2-alpine
    ports:
      - "6379:6379"
    networks:
      - redis-net

  wiremock:
    container_name: wiremock-books
    image: wiremock/wiremock
    ports:
      - '8090:8080'
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --global-response-templating
    networks:
      - redis-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - redis-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge