version: "3.9"

services:

  app:
    container_name: cache-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: cluster
    ports:
      - "8080:8080"
    depends_on:
      - redis-cluster
      - wiremock
    networks:
      redis-net:
        ipv4_address: 172.20.0.10

  wiremock:
    image: wiremock/wiremock
    ports:
      - '8090:8080'
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      redis-net:
        ipv4_address: 172.20.0.20

  redis-cluster:
    image: redis:7.2-rc2-alpine
    command: redis-cli --cluster create 172.20.0.31:6371 172.20.0.32:6372 172.20.0.33:6373 172.20.0.34:6374 172.20.0.35:6375 172.20.0.36:6376 --cluster-replicas 1 --cluster-yes
    networks:
      redis-net:
        ipv4_address: 172.20.0.30
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-1-replica
      - redis-node-2-replica
      - redis-node-3-replica

  redis-node-1:
    container_name: redis-node-1
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6371:6371'
    volumes:
      - ./redis-conf-cluster/node1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.31

  redis-node-2:
    container_name: redis-node-2
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6372:6372'
    volumes:
      - ./redis-conf-cluster/node2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.32

  redis-node-3:
    container_name: redis-node-3
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6373:6373'
    volumes:
      - ./redis-conf-cluster/node3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.33

  redis-node-1-replica:
    container_name: redis-node-1-replica
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6374:6374'
    volumes:
      - ./redis-conf-cluster/node1-replica.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.34
  redis-node-2-replica:
    container_name: redis-node-2-replica
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6375:6375'
    volumes:
      - ./redis-conf-cluster/node2-replica.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.35

  redis-node-3-replica:
    container_name: redis-node-3-replica
    image: redis:7.2-rc2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6376:6376'
    volumes:
      - ./redis-conf-cluster/node3-replica.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.36

networks:
  redis-net:
    name: redis-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24