spring:

  cache:
    type: redis

  data:
    redis:
      cluster:
        nodes:
          - 172.20.0.31:6371
          - 172.20.0.32:6372
          - 172.20.0.33:6373
          - 172.20.0.34:6374
          - 172.20.0.35:6375
          - 172.20.0.36:6376
        max-redirects: 2

      lettuce:
        cluster:
          refresh:
            period: 5000