spring:

  cache:
    type: redis

  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - redis-sentinel-1:5001
          - redis-sentinel-2:5002
          - redis-sentinel-3:5003